### ISSUE TITLE
Extend uploader to read config from package.json

### ISSUE THREAD

**Issue by hrbu** [cubbles/cubx-webpackage-uploader#1]
The next generation of Cubbles developer tools will be used as npm dependency of the webpackage itself. So each webpackage will have a `package.json` with the uploader defined as dependency.

# AsIs
The uploader expects its configuration within a `config.js` (path provided as cli argument).

# ToBe
We want to use the fact the `package.json` is extensible and move the uploader configuration into.
```
# package.json
name: "my-package",
...
devDependencies: [...],
...
cubbles: {
  devTools: {
    cubx-webpackage-uploader: { 
      dev: {
        source": "test/testdata/packages/package1",
        target": {
          url: "http://localhost:5984/sandbox",
          path: "_api/upload",
          proxy: "http://proxy.de:80"
        },
        debug: true
     }
   }
  }
}
```

**Comment by edwingamboa** [comment]
Moved to  https://github.com/cubbles/coder-toolset/issues/8

**Comment by edwingamboa** [comment]
@hrbu I have no permission to close this issue, I moved (copied) it to coder-toolset, but I'm not able to close it here.
